### ISSUE TITLE
YAML structures

### ISSUE THREAD

**Issue by smartacus** [HipByte/motion-yaml#5]
YAML structures aren't working in motion-yaml.

Here's a quick example showing the differences I see between the default Ruby 2.0 parser and the motion-yaml parser:

```ruby
# Ruby 2.0 YAML parser
require 'yaml'
YAML.load('--- "abc" ...')
=> "abc"

# motion-yaml
YAML.load('--- "abc" ...')
=> []
```

**Comment by Watson1978** [comment]
This issue should be fixed with https://github.com/Watson1978/yamlkit/commit/8616635075415ca5565fae170b926736873f6844
